### ISSUE TITLE
对编译说明的请教

### ISSUE THREAD

**Issue by nnnpa31** [benjaminwan/OcrLiteOnnx#2]
Chineseocr_lite 目前主要使用的版本是基于 onnx 的，在您的编译说明中对于 Linux 是这样写的：
> 1. Ubuntu18.04 LTS 其它发行版(请自行编译依赖库opencv和`ncnn`，或自行适配官方发布的动态库)

请问确定这里是要使用 ncnn 吗？而不是自行编译 onnxruntime ？

**Comment by benjaminwan** [comment]
这里写的有误，ncnn应该改为onnxruntime

**Comment by nnnpa31** [comment]
感谢澄清
